Admin page
Emmastro/tatu-ip-group3 pull request #4
Opened 2022-07-03 12:03 UTC by christianadebambo

add admin index page, create post page and css

2022-07-03 12:05 UTC, christianadebambo commented
hi guys, please give reviews and suggestions.

2022-07-04 10:13 UTC, Emmastro requested changes
@christianadebambo, can you add view functions on the views.py file, and a URL on the urls.py file, and test it running the django server? I have also left some comments on the code, but it looks good, just a few changes to make

2022-07-04 10:13 UTC, Emmastro commented on home/templates/admin_create.html
> +
Can you use the base.html, and inherit its content and style here? You can check how it's being used on the other templates.

2022-07-04 10:13 UTC, Emmastro commented on home/templates/admin_index.html
> +<!DOCTYPE html>
same as the admin_create, it should include the base.html file.

2022-07-04 10:13 UTC, Emmastro commented on home/static/css/admin_style.css
> +* {
Can we consolidate the styles, some of the style you have here, or at least similar style, have been written by other members. Just to keep it all consistent, you can refactor and reuse the styles from the existing .css, and only keep here the style specific to the admin page if any

2022-07-17 07:27 UTC, closed without merging